# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5528897e7cfad2c2b4cc46d596880f32f23fbc2dc82c6f4ac49ddcd62a751b1494e254ca58d84bf17601a99dffbc2cfa39ab6f186cc62befcad7200ea0e56adb

test:
  secret_key_base: a88b492fd2023849aa973355ec30ab74603501f6964fef92cacfa0241911d97fb80025cd9a4df4e60ac75dbdfc6daa1b48a49351acbd3e9b7f51416706cc3edd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
